[ERROR] [1720647170.789052]: bad callback: <bound method frame_process.frame_callback of <__main__.frame_process object at 0xfffef977e040>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/orin/air_dmg_assesment_ws/src/yolo_ros/src/yolo_orin_ros.py", line 66, in frame_callback
    dict_string = json.dumps(track_entry)
  File "/usr/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
TypeError: keys must be str, int, float, bool or None, not tuple
